# ========== TEMELJNE POSTAVKE ==========
spring:
  application:
    name: backend

  # ====== POSTAVKE BAZE PODATAKA ======
  datasource:
    url: jdbc:postgresql://localhost:5432/juliusmeinl
    username: postgres
    password: bazapodataka
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        session:
          cookie:
          serializer:
            same-site: none
            use-secure-cookie: true
          store-type: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}


# ========== SERVER CONFIGURATION ==========
server:
  port: ${PORT:8080}
  # forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false



# ========== LOGGING LEVELS ==========
logging:
  level:
    #    root: DEBUG
    org:
      apache:
        http: DEBUG
      springframework:
        web: DEBUG
        security:
          .: DEBUG
          oauth2: DEBUG
#      hibernate: DEBUG

frontend:
    url: http://localhost:5173
  # url: https://bluedilla.onrender.com





